services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: 
    - "5432:5432"
    volumes:
      - ./resources/db/init/:/docker-entrypoint-initdb.d/
      
  redis:
    image: redis:6-alpine
    ports: 
    - "6379:6379"
networks:
  default:
    name: ion-network